version: '3.8'
services:

    gateway:
        build:
            context: ./gateway
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - PORT=3000
            - AWS_REGION=us-east-1
            - AWS_ENDPOINT=http://localstack:4566/000000000000
            - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
            - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - DATABASE_URL=postgres://postgres:postgres@database:5432/hello
        depends_on:
            - localstack
            - database
        networks:
            - app-network

    localstack:
        image: localstack/localstack:latest
        ports:
            - '4566:4566'
        environment:
            - SERVICES=sqs
            - DEFAULT_REGION=us-east-1
            - HOSTNAME_EXTERNAL=localstack
        volumes:
            - './localstack:/docker-entrypoint-initaws.d'
        networks:
            - app-network


    database:
        image: postgres:16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: hello
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network


    create-user:
        build:
            context: .
            dockerfile: ./tools/docker/lambda-base/Dockerfile
            args:
                - SERVICE_PATH=./tools/apps/create-user/src
                - LAMBDA_NAME=create-user
        environment:
            - AWS_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
            - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - AWS_ENDPOINT=http://localstack:4566/000000000000
            - DATABASE_URL=postgres://postgres:postgres@database:5432/hello
        depends_on:
            - localstack
            - database
        networks:
            - app-network


    get-user:
        build:
            context: .
            dockerfile: ./tools/docker/lambda-base/Dockerfile
            args:
                - SERVICE_PATH=./tools/apps/get-user/src
                - LAMBDA_NAME=get-user
        environment:
            - AWS_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
            - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - AWS_ENDPOINT=http://localstack:4566/000000000000
            - DATABASE_URL=postgres://postgres:postgres@database:5432/hello
        depends_on:
            - localstack
            - database
        networks:
            - app-network


    update-user:
        build:
            context: .
            dockerfile: ./tools/docker/lambda-base/Dockerfile
            args:
                - SERVICE_PATH=./tools/apps/update-user/src
                - LAMBDA_NAME=update-user
        environment:
            - AWS_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
            - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - AWS_ENDPOINT=http://localstack:4566/000000000000
            - DATABASE_URL=postgres://postgres:postgres@database:5432/hello
        depends_on:
            - localstack
            - database
        networks:
            - app-network

networks:
    app-network:
        name: app-network
volumes:
    db_data:
